######################################################################
##
## Filename: calc_core_tb.udo
## Created on: Thu Nov 29 5:52:56 PM Pacific Standard Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
