######################################################################
##
## Filename: main_calc_cu.udo
## Created on: Thu Nov 29 6:16:22 PM Pacific Standard Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
